apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-volume
  labels:
    app: nginx
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/kiran"